model: checkpoints/model.de-en.softmax_step_175000.pt
src: data/wmt-2016-en-de/test.en
tgt: data/wmt-2016-en-de/test.de
output: data/wmt-2016-en-de/softmax_pred.txt
replace_unk: 'true'
verbose: 'true'
report_bleu: 'true'
gpu: 0
log_file: logs/softmax_test
attn_out: results/attn_out/softmax.pt
beam_score_out: results/beam_score_out/softmax.pt