data: examples/data/wmt_2014_en_de
save_model: checkpoints/model.de-en.esoftmax
save_checkpoint_steps: 1000
keep_checkpoint: 20
seed: 3435
train_steps: 250000
valid_steps: 1000
warmup_steps: 8000
report_every: 100
# train_steps: 100
# valid_steps: 5
# warmup_steps: 5
# report_every: 1

# loss_fn: esoftmax
self_attention_function: esoftmax
context_attention_function: esoftmax
# gpu_verbose_level: 1

decoder_type: transformer
encoder_type: transformer
word_vec_size: 128
rnn_size: 128
layers: 3
transformer_ff: 512
heads: 8

accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 512
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 1
gpu_ranks:
- 0
